"""Safe, review-first scaffolding for agent harness integrations."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final

from . import __version__


class EquipError(ValueError):
    """Raised when a project cannot be equipped without unsafe assumptions."""


SUPPORTED_FRAMEWORKS: Final = ("langgraph", "crewai", "openai-agents", "generic")
SUPPORTED_AGENT_HOSTS: Final = ("codex", "claude-code", "generic")
_MARKER = "Generated by Mendmark equip; safe to regenerate."
_DEPENDENCY_FILES = (
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "uv.lock",
    "poetry.lock",
    "pdm.lock",
)


def detect_frameworks(project_root: Path) -> tuple[str, ...]:
    """Detect supported harness names from bounded dependency-file reads."""
    corpus: list[str] = []
    for name in _DEPENDENCY_FILES:
        path = project_root / name
        if path.is_file() and path.stat().st_size <= 2_000_000:
            corpus.append(path.read_text(encoding="utf-8", errors="replace").lower())
    text = "\n".join(corpus)
    found: list[str] = []
    if "langgraph" in text or "langchain" in text:
        found.append("langgraph")
    if "crewai" in text:
        found.append("crewai")
    if "openai-agents" in text or "openai_agents" in text:
        found.append("openai-agents")
    return tuple(found or ("generic",))


def detect_agent_hosts(project_root: Path) -> tuple[str, ...]:
    """Detect repository coding-agent conventions without reading their contents."""
    found: list[str] = []
    if any(
        (project_root / name).exists()
        for name in ("AGENTS.md", "AGENTS.override.md", ".agents", ".codex")
    ):
        found.append("codex")
    if any(
        (project_root / name).exists()
        for name in ("CLAUDE.md", "CLAUDE.local.md", ".claude")
    ):
        found.append("claude-code")
    return tuple(found or ("generic",))


def resolve_agent_hosts(project_root: Path, agent: str) -> tuple[str, ...]:
    """Resolve a CLI agent selector to concrete instruction targets."""
    if agent == "auto":
        return detect_agent_hosts(project_root)
    if agent == "all":
        return ("codex", "claude-code", "generic")
    if agent not in SUPPORTED_AGENT_HOSTS:
        raise EquipError(f"unsupported coding agent: {agent}")
    return (agent,)


def agent_prompt(project_root: str = ".", *, agent: str = "generic") -> str:
    """Return the short prompt a user can give any repository coding agent."""
    invocation = {
        "codex": "After setup, use `$mendmark` for future Mendmark work. ",
        "claude-code": "After setup, use `/mendmark` for future Mendmark work. ",
        "generic": "",
        "auto": "",
        "all": "",
    }.get(agent)
    if invocation is None:
        raise EquipError(f"unsupported coding agent: {agent}")
    return (
        f"In {project_root}, run `mendmark equip --framework auto --agent {agent}`, "
        "then read `.mendmark/SELF-EQUIP.md` and `.mendmark/agent-setup.md` "
        "completely. " + invocation + "Integrate the detected harness, "
        "capture at least one reviewed tool-using case, run the local audit, and "
        "satisfy every acceptance criterion before enabling the generated CI "
        "workflow. Do not upload trace content or approve observed behavior "
        "without human review."
    )


def _universal_protocol() -> str:
    return f'''<!-- {_MARKER} -->
# Mendmark self-equip protocol

This is the portable instruction contract for any repository-capable coding
agent, including agents Mendmark does not recognize.

## Objective

Add a local, reviewed mutation-test gate for this repository's agent evaluator.
Success means important mistakes in tool selection, arguments, results,
ordering, coordination, and final outcomes make the evaluator fail.

## Procedure

1. Read `.mendmark/agent-setup.md` completely and inspect the repository's
   dependency manifests, agent entry points, tool definitions, existing tests,
   and CI conventions. Do not execute untrusted project code merely to detect a
   framework.
2. Use a native adapter when listed in the setup guide. Otherwise implement the
   framework-neutral JSON 2.0 contract; preserve stable tool-call IDs and
   explicit causal dependencies rather than inferring causality from time.
3. Identify at least one consequential tool-using path. Capture prompts,
   arguments, results, side effects, handoffs, and expected outcomes locally.
   Redact credentials and personal data before they enter fixtures or reports.
4. Ask a human to review the candidate golden behavior. Never convert an
   observed trace into expected behavior silently; `approve_observed=True` is
   allowed only during that explicit, one-off review boundary.
5. Run the exact local audit command from `agent-setup.md`. Investigate every
   survivor and strengthen the evaluator or document a deliberate exception.
6. Create and review a baseline only after the original cases pass. Do not
   activate the generated CI workflow until the local audit and acceptance
   checklist pass.
7. Report files changed, cases covered, mutation score, survivors, redactions,
   and any remaining risks. Stop and ask for direction if repository policy,
   missing credentials, or destructive actions block safe completion.

## Non-negotiable boundaries

- Keep traces local; Mendmark requires no hosted service or telemetry upload.
- Do not call production side-effecting tools while building fixtures.
- Do not overwrite existing project or agent instruction files.
- Do not weaken tests, evaluator thresholds, branch protection, or CI to pass.
- Do not commit secrets, raw customer data, generated reports, or credentials.
'''


def _agent_skill(agent: str) -> str:
    invocation = "$mendmark" if agent == "codex" else "/mendmark"
    return f'''---
name: mendmark
description: Equip, audit, or improve this repository's agent evaluations with Mendmark. Use when asked about agent eval quality, golden traces, tool-call assurance, multi-agent coordination, mutation testing, or Mendmark setup.
---

# Mendmark agent-evaluation assurance

Read `.mendmark/SELF-EQUIP.md` and `.mendmark/agent-setup.md` completely, then
follow them in that order. Treat their human-review, privacy, production-side-
effect, baseline, and CI boundaries as mandatory. Preserve unrelated work and
existing repository instructions.

When invoked without a narrower request, perform the full self-equip procedure.
Before finishing, run the local audit and summarize coverage, mutation results,
survivors, changed files, and remaining risks. If the generated files are
missing, install the pinned Mendmark version used by the repository and run
`mendmark equip --framework auto --agent {agent}` first.

Users can invoke this workflow explicitly as `{invocation}`.
'''


def _openai_skill_metadata() -> str:
    return '''interface:
  display_name: "Mendmark Assurance"
  short_description: "Mutation-test agent evaluations and golden traces"
  default_prompt: "Use $mendmark to equip and audit this repository's agent evaluations."
policy:
  allow_implicit_invocation: true
'''


def _evaluator() -> str:
    return f'''#!/usr/bin/env python3
"""{_MARKER}

Offline exact evaluator for reviewed Mendmark trace snapshots.
"""
from __future__ import annotations

import json
import sys


def main() -> int:
    request = json.load(sys.stdin)
    evaluations = []
    for requested in request["evaluations"]:
        case = requested["case"]
        tools_match = case.get("tools_called", []) == case.get("expected_tools", [])
        output_matches = (
            case.get("expected_output") is None
            or case.get("actual_output") == case.get("expected_output")
        )
        events_match = case.get("events", []) == case.get("expected_events", [])
        is_multi = "events" in case or "expected_events" in case
        results = [
            {{
                "name": "Reviewed tool trace",
                "score": float(tools_match),
                "passed": tools_match,
                "reason": "Actual tool calls match the reviewed expected calls.",
            }},
            {{
                "name": "Reviewed outcome",
                "score": float(output_matches),
                "passed": output_matches,
                "reason": "The outcome matches when an expected outcome is configured.",
            }},
        ]
        if is_multi:
            results.append(
                {{
                    "name": "Reviewed coordination graph",
                    "score": float(events_match),
                    "passed": events_match,
                    "reason": "Actual causal events match the reviewed graph.",
                }}
            )
        evaluations.append(
            {{"evaluation_id": requested["evaluation_id"], "results": results}}
        )
    json.dump(
        {{"schema_version": request["schema_version"], "evaluations": evaluations}},
        sys.stdout,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _adapter_example(framework: str) -> str:
    if framework == "langgraph":
        return '''```python
from mendmark.integrations.langchain import case_from_messages, tool_specs
from mendmark.integrations import write_suite

# `result` is the graph/agent state and `tools` is the configured tool list.
case = case_from_messages(
    result["messages"],
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(tools, side_effecting=["refund_order"]),
)
```'''
    if framework == "openai-agents":
        return '''```python
from mendmark.integrations.openai_agents import case_from_result, tool_specs
from mendmark.integrations import write_suite

# `result` is returned by Runner.run/run_sync and `agent` is the configured Agent.
case = case_from_result(
    result,
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(agent.tools, side_effecting=["refund_order"]),
)
```'''
    if framework == "crewai":
        return '''```python
from mendmark.integrations.crewai import CrewAIRecorder, tool_specs
from mendmark.integrations import write_suite

recorder = CrewAIRecorder().attach()  # Attach before crew.kickoff().
result = crew.kickoff(inputs=test_inputs)
case = recorder.case(
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(all_tools, side_effecting=["refund_order"]),
)
```'''
    return '''Use the framework-neutral JSON contract documented at
`https://github.com/danielgaskins/mendmark/blob/main/docs/json-adapter.md`.
Create a reviewed suite at `.mendmark/suite.json`; do not send trace content to
Mendmark or any hosted service.'''


def _instructions(frameworks: tuple[str, ...]) -> str:
    detected = ", ".join(frameworks)
    examples = "\n\n".join(
        f"### {framework}\n\n{_adapter_example(framework)}" for framework in frameworks
    )
    return f'''<!-- {_MARKER} -->
# Equip this repository with Mendmark

Detected integration: **{detected}**.

Mendmark mutation-tests the evaluator, not the agent. Keep all trace content
local. The generated exact evaluator is a safe starting point for reviewed
snapshots; replace or supplement it with the project's real evaluator when
available.

## Capture a reviewed case

{examples}

`approve_observed=True` is deliberately explicit. Inspect tool names,
arguments, results, ordering, side effects, and the expected outcome before
running the capture. Prefer passing an explicit `expected_tools` sequence in a
maintained capture test. Never turn arbitrary production traces into expected
behavior automatically.

## Run locally

```bash
mendmark audit-json .mendmark/suite.json \\
  --evaluator-command "python .mendmark/evaluator.py" \\
  --output .mendmark/report.json \\
  --junit .mendmark/report.xml \\
  --sarif .mendmark/report.sarif
```

Review every survivor. When the suite is accepted, create its baseline once
with `--write-baseline`, review `.mendmark/baseline.json`, and commit it. Copy
`.mendmark/mendmark-ci.yml` to `.github/workflows/mendmark.yml` only after the
local command passes.

## Acceptance criteria

- [ ] At least one consequential, tool-using case is captured.
- [ ] A human reviewed expected calls, arguments, outputs, order, and outcome.
- [ ] Every side-effecting tool is declared with `side_effecting=True`.
- [ ] The original case passes before mutation.
- [ ] Critical survivors were fixed or explicitly documented and accepted.
- [ ] No prompt, arguments, result content, credentials, or PII appears in the report.
- [ ] The baseline was generated only from a passing audit and reviewed in diff.
- [ ] The generated CI workflow passes on a pull request before becoming required.

For native multi-agent coordination mutation testing, model the causal graph
with `mendmark.integrations.CausalCaseBuilder` instead of flattening it into an
ordered tool trace. See `docs/multi-agent.md` in Mendmark's repository.
'''


def _workflow() -> str:
    return f'''# {_MARKER}
name: mendmark

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  agent-eval-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"
          cache: pip
      - run: python -m pip install . 'mendmark-evals=={__version__}'
      - name: Mutation-test agent evals
        run: >-
          mendmark audit-json .mendmark/suite.json
          --evaluator-command "python .mendmark/evaluator.py"
          --baseline .mendmark/baseline.json
          --output .mendmark/report.json
          --junit .mendmark/report.xml
          --sarif .mendmark/report.sarif
          --maximum-mutants 10000
      - uses: github/codeql-action/upload-sarif@b374143c1149a911a7c303ebe6abb5c19149a01c # v3
        if: always() && hashFiles('.mendmark/report.sarif') != ''
        continue-on-error: true
        with:
          sarif_file: .mendmark/report.sarif
'''


def _files(
    frameworks: tuple[str, ...], agent_hosts: tuple[str, ...]
) -> dict[str, str]:
    generated = {
        ".mendmark/evaluator.py": _evaluator(),
        ".mendmark/agent-setup.md": _instructions(frameworks),
        ".mendmark/SELF-EQUIP.md": _universal_protocol(),
        ".mendmark/mendmark-ci.yml": _workflow(),
        ".mendmark/config.json": json.dumps(
            {
                "agent_hosts": list(agent_hosts),
                "frameworks": list(frameworks),
                "schema_version": "1.0",
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        ".mendmark/.gitignore": (
            f"# {_MARKER}\nreport.json\nreport.xml\nreport.sarif\n"
        ),
    }
    if "codex" in agent_hosts:
        generated[".agents/skills/mendmark/SKILL.md"] = _agent_skill("codex")
        generated[".agents/skills/mendmark/agents/openai.yaml"] = (
            _openai_skill_metadata()
        )
    if "claude-code" in agent_hosts:
        generated[".claude/skills/mendmark/SKILL.md"] = _agent_skill("claude-code")
    return generated


def equip_project(
    project_root: str | Path,
    *,
    framework: str = "auto",
    agent: str = "auto",
    dry_run: bool = False,
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """Create non-destructive integration assets.

    Returns ``(frameworks, created, unchanged)``. Existing differing files are
    never overwritten; the user must review and resolve them manually.
    """
    root = Path(project_root).expanduser().resolve()
    if not root.is_dir():
        raise EquipError(f"project root is not a directory: {root}")
    if framework != "auto" and framework not in SUPPORTED_FRAMEWORKS:
        raise EquipError(f"unsupported framework: {framework}")
    frameworks = detect_frameworks(root) if framework == "auto" else (framework,)
    agent_hosts = resolve_agent_hosts(root, agent)
    generated = _files(frameworks, agent_hosts)
    created: list[str] = []
    unchanged: list[str] = []
    conflicts: list[str] = []
    for relative, content in generated.items():
        destination = root / relative
        resolved_destination = destination.resolve()
        if root not in resolved_destination.parents:
            conflicts.append(relative)
            continue
        if destination.exists():
            if destination.is_symlink() or not destination.is_file():
                conflicts.append(relative)
            elif destination.read_text(encoding="utf-8") == content:
                unchanged.append(relative)
            else:
                conflicts.append(relative)
        else:
            created.append(relative)
    if conflicts:
        raise EquipError(
            "refusing to overwrite existing integration file(s): "
            + ", ".join(conflicts)
        )
    if not dry_run:
        for relative in created:
            destination = root / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            if root not in destination.resolve().parents:
                raise EquipError(f"integration path escapes project root: {relative}")
            destination.write_text(generated[relative], encoding="utf-8")
    return frameworks, tuple(created), tuple(unchanged)
