"""Safe, review-first scaffolding for agent harness integrations."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final

from . import __version__


class EquipError(ValueError):
    """Raised when a project cannot be equipped without unsafe assumptions."""


SUPPORTED_FRAMEWORKS: Final = ("langgraph", "crewai", "openai-agents", "generic")
_MARKER = "Generated by Mendmark equip; safe to regenerate."
_DEPENDENCY_FILES = (
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "uv.lock",
    "poetry.lock",
    "pdm.lock",
)


def detect_frameworks(project_root: Path) -> tuple[str, ...]:
    """Detect supported harness names from bounded dependency-file reads."""
    corpus: list[str] = []
    for name in _DEPENDENCY_FILES:
        path = project_root / name
        if path.is_file() and path.stat().st_size <= 2_000_000:
            corpus.append(path.read_text(encoding="utf-8", errors="replace").lower())
    text = "\n".join(corpus)
    found: list[str] = []
    if "langgraph" in text or "langchain" in text:
        found.append("langgraph")
    if "crewai" in text:
        found.append("crewai")
    if "openai-agents" in text or "openai_agents" in text:
        found.append("openai-agents")
    return tuple(found or ("generic",))


def agent_prompt(project_root: str = ".") -> str:
    """Return the short prompt a user can give any repository coding agent."""
    return (
        f"In {project_root}, run `mendmark equip --framework auto`, then read "
        "`.mendmark/agent-setup.md` completely. Integrate the detected harness, "
        "capture at least one reviewed tool-using case, run the local audit, and "
        "satisfy every acceptance criterion before enabling the generated CI "
        "workflow. Do not upload trace content or approve observed behavior "
        "without human review."
    )


def _evaluator() -> str:
    return f'''#!/usr/bin/env python3
"""{_MARKER}

Offline exact evaluator for reviewed Mendmark trace snapshots.
"""
from __future__ import annotations

import json
import sys


def main() -> int:
    request = json.load(sys.stdin)
    evaluations = []
    for requested in request["evaluations"]:
        case = requested["case"]
        tools_match = case.get("tools_called", []) == case.get("expected_tools", [])
        output_matches = (
            case.get("expected_output") is None
            or case.get("actual_output") == case.get("expected_output")
        )
        events_match = case.get("events", []) == case.get("expected_events", [])
        is_multi = "events" in case or "expected_events" in case
        results = [
            {{
                "name": "Reviewed tool trace",
                "score": float(tools_match),
                "passed": tools_match,
                "reason": "Actual tool calls match the reviewed expected calls.",
            }},
            {{
                "name": "Reviewed outcome",
                "score": float(output_matches),
                "passed": output_matches,
                "reason": "The outcome matches when an expected outcome is configured.",
            }},
        ]
        if is_multi:
            results.append(
                {{
                    "name": "Reviewed coordination graph",
                    "score": float(events_match),
                    "passed": events_match,
                    "reason": "Actual causal events match the reviewed graph.",
                }}
            )
        evaluations.append(
            {{"evaluation_id": requested["evaluation_id"], "results": results}}
        )
    json.dump(
        {{"schema_version": request["schema_version"], "evaluations": evaluations}},
        sys.stdout,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _adapter_example(framework: str) -> str:
    if framework == "langgraph":
        return '''```python
from mendmark.integrations.langchain import case_from_messages, tool_specs
from mendmark.integrations import write_suite

# `result` is the graph/agent state and `tools` is the configured tool list.
case = case_from_messages(
    result["messages"],
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(tools, side_effecting=["refund_order"]),
)
```'''
    if framework == "openai-agents":
        return '''```python
from mendmark.integrations.openai_agents import case_from_result, tool_specs
from mendmark.integrations import write_suite

# `result` is returned by Runner.run/run_sync and `agent` is the configured Agent.
case = case_from_result(
    result,
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(agent.tools, side_effecting=["refund_order"]),
)
```'''
    if framework == "crewai":
        return '''```python
from mendmark.integrations.crewai import CrewAIRecorder, tool_specs
from mendmark.integrations import write_suite

recorder = CrewAIRecorder().attach()  # Attach before crew.kickoff().
result = crew.kickoff(inputs=test_inputs)
case = recorder.case(
    case_id="reviewed-order-flow",
    input=test_input,
    expected_output=reviewed_expected_output,
    approve_observed=True,  # Only in the one-off capture after human review.
)
write_suite(
    ".mendmark/suite.json",
    [case],
    tool_specs(all_tools, side_effecting=["refund_order"]),
)
```'''
    return '''Use the framework-neutral JSON contract documented at
`https://github.com/danielgaskins/mendmark/blob/main/docs/json-adapter.md`.
Create a reviewed suite at `.mendmark/suite.json`; do not send trace content to
Mendmark or any hosted service.'''


def _instructions(frameworks: tuple[str, ...]) -> str:
    detected = ", ".join(frameworks)
    examples = "\n\n".join(
        f"### {framework}\n\n{_adapter_example(framework)}" for framework in frameworks
    )
    return f'''<!-- {_MARKER} -->
# Equip this repository with Mendmark

Detected integration: **{detected}**.

Mendmark mutation-tests the evaluator, not the agent. Keep all trace content
local. The generated exact evaluator is a safe starting point for reviewed
snapshots; replace or supplement it with the project's real evaluator when
available.

## Capture a reviewed case

{examples}

`approve_observed=True` is deliberately explicit. Inspect tool names,
arguments, results, ordering, side effects, and the expected outcome before
running the capture. Prefer passing an explicit `expected_tools` sequence in a
maintained capture test. Never turn arbitrary production traces into expected
behavior automatically.

## Run locally

```bash
mendmark audit-json .mendmark/suite.json \\
  --evaluator-command "python .mendmark/evaluator.py" \\
  --output .mendmark/report.json \\
  --junit .mendmark/report.xml \\
  --sarif .mendmark/report.sarif
```

Review every survivor. When the suite is accepted, create its baseline once
with `--write-baseline`, review `.mendmark/baseline.json`, and commit it. Copy
`.mendmark/mendmark-ci.yml` to `.github/workflows/mendmark.yml` only after the
local command passes.

## Acceptance criteria

- [ ] At least one consequential, tool-using case is captured.
- [ ] A human reviewed expected calls, arguments, outputs, order, and outcome.
- [ ] Every side-effecting tool is declared with `side_effecting=True`.
- [ ] The original case passes before mutation.
- [ ] Critical survivors were fixed or explicitly documented and accepted.
- [ ] No prompt, arguments, result content, credentials, or PII appears in the report.
- [ ] The baseline was generated only from a passing audit and reviewed in diff.
- [ ] The generated CI workflow passes on a pull request before becoming required.

For native multi-agent coordination mutation testing, model the causal graph
with `mendmark.integrations.CausalCaseBuilder` instead of flattening it into an
ordered tool trace. See `docs/multi-agent.md` in Mendmark's repository.
'''


def _workflow() -> str:
    return f'''# {_MARKER}
name: mendmark

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  agent-eval-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.13"
          cache: pip
      - run: python -m pip install . 'mendmark-evals=={__version__}'
      - name: Mutation-test agent evals
        run: >-
          mendmark audit-json .mendmark/suite.json
          --evaluator-command "python .mendmark/evaluator.py"
          --baseline .mendmark/baseline.json
          --output .mendmark/report.json
          --junit .mendmark/report.xml
          --sarif .mendmark/report.sarif
          --maximum-mutants 10000
      - uses: github/codeql-action/upload-sarif@b374143c1149a911a7c303ebe6abb5c19149a01c # v3
        if: always() && hashFiles('.mendmark/report.sarif') != ''
        continue-on-error: true
        with:
          sarif_file: .mendmark/report.sarif
'''


def _files(frameworks: tuple[str, ...]) -> dict[str, str]:
    return {
        ".mendmark/evaluator.py": _evaluator(),
        ".mendmark/agent-setup.md": _instructions(frameworks),
        ".mendmark/mendmark-ci.yml": _workflow(),
        ".mendmark/config.json": json.dumps(
            {"schema_version": "1.0", "frameworks": list(frameworks)},
            indent=2,
            sort_keys=True,
        )
        + "\n",
        ".mendmark/.gitignore": (
            f"# {_MARKER}\nreport.json\nreport.xml\nreport.sarif\n"
        ),
    }


def equip_project(
    project_root: str | Path,
    *,
    framework: str = "auto",
    dry_run: bool = False,
) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    """Create non-destructive integration assets.

    Returns ``(frameworks, created, unchanged)``. Existing differing files are
    never overwritten; the user must review and resolve them manually.
    """
    root = Path(project_root).expanduser().resolve()
    if not root.is_dir():
        raise EquipError(f"project root is not a directory: {root}")
    if framework != "auto" and framework not in SUPPORTED_FRAMEWORKS:
        raise EquipError(f"unsupported framework: {framework}")
    frameworks = detect_frameworks(root) if framework == "auto" else (framework,)
    generated = _files(frameworks)
    created: list[str] = []
    unchanged: list[str] = []
    conflicts: list[str] = []
    for relative, content in generated.items():
        destination = root / relative
        resolved_destination = destination.resolve()
        if root not in resolved_destination.parents:
            conflicts.append(relative)
            continue
        if destination.exists():
            if destination.is_symlink() or not destination.is_file():
                conflicts.append(relative)
            elif destination.read_text(encoding="utf-8") == content:
                unchanged.append(relative)
            else:
                conflicts.append(relative)
        else:
            created.append(relative)
    if conflicts:
        raise EquipError(
            "refusing to overwrite existing integration file(s): "
            + ", ".join(conflicts)
        )
    if not dry_run:
        for relative in created:
            destination = root / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            if root not in destination.resolve().parents:
                raise EquipError(f"integration path escapes project root: {relative}")
            destination.write_text(generated[relative], encoding="utf-8")
    return frameworks, tuple(created), tuple(unchanged)
